<?php

namespace App\Http\Requests;

use App\Models\Producto;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreProductoRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'nombre' => 'required|string',
            'descripcion' => 'required|string',
            'foto' => 'required|image',
            'cantidad' => 'required|integer',
            'precio' => 'required|integer',
            'iva' => ['required', 'integer', Rule::in(Producto::IVA)],
            'vendedor_id' => 'required|exists:App\Models\Vendedor,id'
        ];
    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'iva.in' => 'El iva no es válido, elija entre: ' . implode(', ', Producto::IVA)
        ];
    }
}
