<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cliente extends User
{
    use HasFactory;

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope('cliente', function (Builder $builder){
            $builder->has('ventas');
        });
    }

    public function ventas()
    {
        return $this->hasMany(Venta::class);
    }
}
