<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Vendedor extends User
{
    use HasFactory;

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope('vendedor', function (Builder $builder){
            $builder->has('productos');
        });
    }

    public function productos()
    {
        return $this->hasMany(Producto::class);
    }
}
